[package]
name = "twilio-exporter"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
metrics = "0.21.1"
metrics-exporter-prometheus = "0.12.1"
rand = "0.8.5"
